[package]
name = "run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.10"
tiny_file_server = "0.1.5"
tiny_http = "0.12.0"
iron = "0.6"
staticfile = "0.5"
mount = "0.4"