[package]
name = "fb"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.10"
iron = "0.6"
staticfile = "0.5"
mount = "0.4" 